### ISSUE TITLE
Different approach suggestion

### ISSUE THREAD

**Issue by costafrancesco94** [rufusmaiwald/lumen-vue-app#7] opened 2020-11-29 18:57 UTC
Hello :)

I used your `vue.config.json` to setup one of my personal project that have a vue-cli instance inside a lumen project.

I have a suggestion for a different approach to the developing of new functionalities:

 1. almost the same of you, but
 1. leave untouched the files in `public` folder. remove only the `index.html` that go in `resources/js/vue/index.html` as you do
 2. don't re-create lumen `public` dir inside `storage/static` as you, but leave as is
 3. in `vue.config.json`, replace `outputDir: './public/'` with `outputDir: './dist/'` or whatever that is not `public`
4.  in `vue.config.json`, comment out the `config.plugins.has('copy') .......` (those lines was not working for me anyway)

Then, while developing, launch the command `vue-cli-service build --watch`, that build the files in the `./dist` folder copying the content of `public` (non-well documented features, or non present features when you write it).

You can put in `package.json` like this:
```json
"scripts": {
....
    "build-watching": "vue-cli-service build --watch",
...
  },
```

Then, you have two different choices:
### setup apache webserver
```conf
<VirtualHost *:80>

        DocumentRoot /path/to/project/lumen-vue-cli/dist
        ServerName lumen-vue-cli.local

        <Directory /path/to/project/lumen-vue-cli/dist>
                AllowOverride All
                Require all granted
        </Directory>

        ErrorLog        /path/to/project/lumen-vue-cli/storage/logs/apache_error.log
        CustomLog      /path/to/project/lumen-vue-cli/storage/logs/access.log          common

        php_value error_log /path/to/project/lumen-vue-cli/storage/logs/php_error.log

        <IfModule mpm_itk_module>
                AssignUserId youruser youruser
        </IfModule>
</VirtualHost>
```
remember to add `127.0.0.1 lumen-vue-cli.local` to your `/etc/hosts` or `C:/windows/system32/drivers/etc/hosts` and to install mod `mpm_itk` to correct user permission
### use artisan built-in webserver
`php -S localhost:8000 -t dist` (and not public)

Don't know if it can be useful, I can do a PR if you want... 

Thank you for your idea :)

**Comment by costafrancesco94** [comment] 2020-11-29 19:08
I forgot to mention that none of this method have the "hot reload" while developing, it just build files and it updated the build when you edit the code (as in `webpack --watch`). Don't know if hot reload is a must have features, maybe it could be implemented through a lumen event and put a little `js` to force the uploading, but my idea is that hot reloading is more an issue than a features sometimes (**sometimes**) - mostly when you are testing api/response: that's becouse the editor will compile the asset and send the "reload page" signal even when you change only php and leave the assets untouched. Maybe it's just me, but I hate when the component reloads the page when i'm reading console...

**Comment by rufusmai** [comment] 2020-12-07 16:26
First of all thank you for your help and interest in this project @costafrancesco94!

As this project got some recent activity by you, I decided to implement some changes that I wanted to some time further but had no time for.

I created this repository with using the built-in vue dev server functionality for development and not any sort of extra web server like apache or nginx, Therefore I don't like the idea of changing the vue build directory to some other than `public`.
Especially if I want to build my app for production I need my assets to be in the `public` folder, if I don't want to use any sort of rewrite logic in `.htaccess` file or other webserver config.

There comes the problem of static files that you need in the `public` folder (like `.htaccess`, `favicon.ico`, ...).
My approach for this was using the webpack copy plugin in `vue.config.js` in line 17.
You said that didn't work for you but I couldn't reproduce the error.

To solve the problem of hot reloading in a dev environment I added the devServer proxy feature in the new `v2` upgrade.
I would love to hear your feedback about this even if it uses a different approach than you described here.
Fell free to comment about any ideas you have to my [v2 PR](https://github.com/rufusmaiwald/lumen-vue-cli/pull/9).

**Comment by rufusmai** [comment] 2020-12-24 14:20
I'll close this, as v2 may solve this issue

**Closed as completed by rufusmai** 2020-12-24 14:20 UTC
